-- Territory hierarchy + VP/Manager/Sales allocation model
-- Safe to rerun: IF NOT EXISTS guards and non-destructive DDL only.

-- 1) Raw postal ingestion table (optional archival of source rows)
CREATE TABLE IF NOT EXISTS public.geo_postal_raw (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_code text,
  state_name text NOT NULL,
  district_code text,
  district_name text,
  subdistrict_code text,
  subdistrict_name text,
  village_code text,
  village_name text,
  pincode text NOT NULL,
  source_file text,
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_geo_postal_raw_state_name ON public.geo_postal_raw(state_name);
CREATE INDEX IF NOT EXISTS idx_geo_postal_raw_pincode ON public.geo_postal_raw(pincode);

-- 2) City-level business divisions
CREATE TABLE IF NOT EXISTS public.geo_divisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  division_key text NOT NULL UNIQUE,
  state_id uuid REFERENCES public.states(id) ON DELETE SET NULL,
  city_id uuid REFERENCES public.cities(id) ON DELETE SET NULL,
  name text NOT NULL,
  slug text NOT NULL,
  district_name text,
  subdistrict_name text,
  pincode_count integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_geo_divisions_state_id ON public.geo_divisions(state_id);
CREATE INDEX IF NOT EXISTS idx_geo_divisions_city_id ON public.geo_divisions(city_id);
CREATE INDEX IF NOT EXISTS idx_geo_divisions_is_active ON public.geo_divisions(is_active);

-- 3) Pincodes mapped to divisions
CREATE TABLE IF NOT EXISTS public.geo_division_pincodes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  division_id uuid NOT NULL REFERENCES public.geo_divisions(id) ON DELETE CASCADE,
  pincode text NOT NULL,
  source_district_name text,
  source_subdistrict_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (division_id, pincode)
);

CREATE INDEX IF NOT EXISTS idx_geo_division_pincodes_division_id ON public.geo_division_pincodes(division_id);
CREATE INDEX IF NOT EXISTS idx_geo_division_pincodes_pincode ON public.geo_division_pincodes(pincode);

-- 4) VP -> Manager division allocation
CREATE TABLE IF NOT EXISTS public.vp_manager_division_allocations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vp_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  manager_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  division_id uuid NOT NULL REFERENCES public.geo_divisions(id) ON DELETE CASCADE,
  allocation_status text NOT NULL DEFAULT 'ACTIVE' CHECK (allocation_status IN ('ACTIVE', 'PAUSED', 'RELEASED')),
  notes text,
  allocated_at timestamptz NOT NULL DEFAULT now(),
  released_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vp_manager_alloc_manager ON public.vp_manager_division_allocations(manager_user_id);
CREATE INDEX IF NOT EXISTS idx_vp_manager_alloc_division ON public.vp_manager_division_allocations(division_id);
CREATE INDEX IF NOT EXISTS idx_vp_manager_alloc_status ON public.vp_manager_division_allocations(allocation_status);

CREATE UNIQUE INDEX IF NOT EXISTS uq_vp_manager_alloc_active
  ON public.vp_manager_division_allocations(manager_user_id, division_id)
  WHERE allocation_status = 'ACTIVE';

-- 5) Manager -> Salesperson division allocation
CREATE TABLE IF NOT EXISTS public.manager_sales_division_allocations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  manager_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  sales_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  division_id uuid NOT NULL REFERENCES public.geo_divisions(id) ON DELETE CASCADE,
  allocation_status text NOT NULL DEFAULT 'ACTIVE' CHECK (allocation_status IN ('ACTIVE', 'PAUSED', 'RELEASED')),
  notes text,
  allocated_at timestamptz NOT NULL DEFAULT now(),
  released_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_manager_sales_alloc_manager ON public.manager_sales_division_allocations(manager_user_id);
CREATE INDEX IF NOT EXISTS idx_manager_sales_alloc_sales ON public.manager_sales_division_allocations(sales_user_id);
CREATE INDEX IF NOT EXISTS idx_manager_sales_alloc_division ON public.manager_sales_division_allocations(division_id);
CREATE INDEX IF NOT EXISTS idx_manager_sales_alloc_status ON public.manager_sales_division_allocations(allocation_status);

CREATE UNIQUE INDEX IF NOT EXISTS uq_manager_sales_alloc_active
  ON public.manager_sales_division_allocations(sales_user_id, division_id)
  WHERE allocation_status = 'ACTIVE';

-- 6) Optional explicit vendor -> division map (fallback can still be city-based)
CREATE TABLE IF NOT EXISTS public.vendor_division_map (
  vendor_id uuid PRIMARY KEY REFERENCES public.vendors(id) ON DELETE CASCADE,
  division_id uuid REFERENCES public.geo_divisions(id) ON DELETE SET NULL,
  mapped_by_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  mapping_source text NOT NULL DEFAULT 'AUTO',
  confidence numeric(5,2),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vendor_division_map_division_id ON public.vendor_division_map(division_id);

-- 7) Sales engagement ledger (masked-contact workflow tracking)
CREATE TABLE IF NOT EXISTS public.sales_vendor_engagements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE,
  sales_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  manager_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  vp_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  division_id uuid REFERENCES public.geo_divisions(id) ON DELETE SET NULL,
  engagement_type text NOT NULL DEFAULT 'FOLLOW_UP' CHECK (
    engagement_type IN ('CALL', 'WHATSAPP', 'VISIT', 'DEMO', 'FOLLOW_UP', 'PLAN_PITCH', 'CONVERTED', 'UNMASK_REQUEST')
  ),
  status text NOT NULL DEFAULT 'OPEN',
  notes text,
  next_follow_up_at timestamptz,
  is_contact_unmasked boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sales_vendor_engagements_vendor_id ON public.sales_vendor_engagements(vendor_id);
CREATE INDEX IF NOT EXISTS idx_sales_vendor_engagements_sales_user_id ON public.sales_vendor_engagements(sales_user_id);
CREATE INDEX IF NOT EXISTS idx_sales_vendor_engagements_manager_user_id ON public.sales_vendor_engagements(manager_user_id);
CREATE INDEX IF NOT EXISTS idx_sales_vendor_engagements_division_id ON public.sales_vendor_engagements(division_id);
CREATE INDEX IF NOT EXISTS idx_sales_vendor_engagements_created_at ON public.sales_vendor_engagements(created_at DESC);
